###
GET http://localhost:5001/api/phones

###
POST http://localhost:5001/api/phones
Content-Type: application/json

{
  "brand": "Samsung",
  "model": "XS",
  "releaseYear": 2025,
  "price": 27999,
  "color": "green",
  "description": "New"
}

###
GET http://localhost:5001/api/phones/6930475d513238022337856c

###
PATCH http://localhost:5001/api/phones/6930475d513238022337856c
Content-Type: application/json

{
  "brand": "Samsung",
  "model": "X9"
}

###
DELETE http://localhost:5001/api/phones/6930475d513238022337856c