### 201 {}

POST http://localhost:5001/api/users
Content-Type: application/json

{
  "firstName":"Testtwo",
  "lastName":"Testovych",
  "email":"t1@t.com",
  "birthday":"2000-01-01",
  "gender": "male",
  "isMerried":true,
  "workExperience": 2
}

### 200 {}

GET http://localhost:5001/api/users?limit=2&skip=1


### 200 {}

GET http://localhost:5001/api/users/65bfb4b98f78c3d93b668251


### 200 {}

PATCH http://localhost:5001/api/users/65bfb4b98f78c3d93b668251
Content-Type: application/json

{
  "firstName":"Test",
  "workExperience": 3
}

### 204 {}

DELETE http://localhost:5001/api/users/65bfb78947967bec71ed83cc

POST http://localhost:5001/api/users/65bfb4b98f78c3d93b668251/posts
Content-Type: application/json

{
  "body":"Some new post 4"
}

GET http://localhost:5001/api/users/6930442914085f9250c5758a/posts

GET http://localhost:5001/api/posts

###
POST http://localhost:5001/api/users/6930442914085f9250c5758a/phones
Content-Type: application/json

{
  "brand": "Apple",
  "model": "iPhone 11",
  "releaseYear": 2020,
  "price": 20999,
  "color": "gold",
  "description": "New"
}

###
GET http://localhost:5001/api/users/6930442914085f9250c5758a/phones